### ISSUE TITLE
缺少scripts/start.js 文件，无法启动项目

### ISSUE THREAD

**Issue by Disat** [ChineseBread/BreadBlog#3]
我按照以下步骤
1. git clone 项目到本地
2. 切换到React-18分支
3. yarn 安装依赖
4. yarn start
报错提示找不到 scripts/start.js文件。

**Comment by ChineseBread** [comment]
等下给你补

**Comment by ChineseBread** [comment]
项目需要自己eject一次，eject后会有script文件夹

**Comment by Disat** [comment]
问题解决了
1. 我使用create-react-app新建一个空项目
2. 执行npm run eject，将新生成的scripts文件夹复制到这个项目里
3. yarn start 可以正常运行了

尝试过在克隆的项目里使用 npx react-scripts eject ，会提示不能覆盖已有的config目录和package.json文件
